version: '3.7'

services:
  users:
    build:
      context: ./users
      dockerfile: Dockerfile-prod
    # volumes:
    #   - './users:/usr/src/app'
    # ports:
    #   - 5001:5000
    environment:
      - FLASK_ENV=production
      - APP_SETTINGS=project.config.ProductionConfig
      - DATABASE_URL=postgres://postgres:postgres@users-db:5432/users_prod
      - DATABASE_TEST_URL=postgres://postgres:postgres@users-db:5432/users_test
    depends_on:
      - users-db
    expose:
      - 5000
      
  users-db:
    build:
      context: ./users/project/db
      dockerfile: Dockerfile
    # ports:
    #   - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - 5432

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile-prod
    restart: always
    ports:
      - 80:80
    depends_on:
      - users