version: '3.7'

services:
  users:
    build:
      context: ./users
      dockerfile: Dockerfile
    volumes:
      - './users:/usr/src/app'
    ports:
      - 5001:5000
    environment:
      - FLASK_APP=project/__init__.py
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@users-db:5432/users_dev
      - DATABASE_TEST=postgres://postgres:postgres@users-db:5432/users_test
    depends_on:
      - users-db
  
  users-db:
    build:
      context: ./users/project/db
      dockerfile: Dockerfile
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres